name: Lint, type-check and format

on:
  push:
    branches:
      - feature/**
      - hotfix/**
  pull_request:
    branches:
      - main
      - feature/**
      - hotfix/**

jobs:
  install-dependencies:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Bun dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lock
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun ci --frozen-lockfile

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Restore Bun cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lock
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - name: Run ESLint
        run: bun run lint:check

  type-check:
    name: Type-Check
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Restore Bun cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lock
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - name: Run TSC
        run: bun run type-check

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Restore Bun cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lock
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - name: Run Prettier
        run: bun run fmt:check
